"""Fix show venue_id mislabel

Revision ID: 4abc2a9ed0da
Revises: f598036d1b4b
Create Date: 2024-08-04 22:23:57.649498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abc2a9ed0da'
down_revision = 'f598036d1b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.drop_column('show_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
