"""fix artist genres.

Revision ID: 5a91175f1822
Revises: 85270ab4c2e2
Create Date: 2024-08-05 10:28:22.559519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a91175f1822'
down_revision = '85270ab4c2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=121)),
               type_=sa.ARRAY(sa.String(length=120)),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.ARRAY(sa.String(length=120)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=121)),
               existing_nullable=True)

    # ### end Alembic commands ###
