"""fix artist genres?

Revision ID: 85270ab4c2e2
Revises: 4abc2a9ed0da
Create Date: 2024-08-05 10:22:46.101882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85270ab4c2e2'
down_revision = '4abc2a9ed0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=121)),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.ARRAY(sa.String(length=121)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
